name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Run tests
        run: |
          deno test --unstable --import-map=deno.json --allow-read --allow-net

      - name: Generate docs
        run: |
          deno doc --html --output=./docs src/Schema.ts

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs
