name: Build and deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Generate docs into ./docs
        run: |
          deno doc --html --output=./docs src/Schema.ts
          echo "Generated files:" && ls -la ./docs || true

      - name: Commit docs to main/docs (attempt)
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs || true
          echo "git status:" && git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore(docs): update generated docs [skip ci]" || true
            # Try a verbose push so logs show more detail if it fails
            if git push origin HEAD:main --verbose; then
              echo "pushed=true" >> $GITHUB_OUTPUT
            else
              echo "pushed=false" >> $GITHUB_OUTPUT
              echo "git push failed with exit code $?" >&2
            fi
          else
            echo "No changes to docs"
            echo "pushed=true" >> $GITHUB_OUTPUT
          fi

      - name: Show remotes and refs
        if: always()
        run: |
          git remote -v || true
          git show-ref || true

      - name: Fallback deploy to gh-pages
        if: steps.commit.outputs.pushed == 'false'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
