name: Build and deploy docs (gh-pages)

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Generate docs into ./docs
        run: |
          deno doc --html --output=./docs src/Schema.ts
          echo "Generated files:" && ls -la ./docs || true

      - name: Git diagnostics
        run: |
          git --version
          git status --porcelain || true
          echo "origin URL:" && git remote get-url origin || true
          echo "refs:" && git show-ref || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use a personal access token if provided (optional). Otherwise fall back to GITHUB_TOKEN.
          personal_token: ${{ secrets.GH_PAGES_PAT || secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
