name: Build and deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Generate docs into ./docs
        run: |
          deno doc --html --output=./docs src/Schema.ts
          echo "Generated files:" && ls -la ./docs || true

      - name: Commit docs to main/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs || true
          echo "git status:" && git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore(docs): update generated docs [skip ci]" || true
            git push origin HEAD:main
          else
            echo "No changes to docs"
          fi
